Fix memory leaks in custom executor
duckdb/pg_duckdb pull request #256
Opened 2024-10-07 14:03 UTC by Y--

When one calls `elog(ERROR,...` it `longjmp` out of the current stack leaving no chance for the C++ to be executed.

This PR is a first iteration toward what we want to rationalize (cf. https://github.com/duckdb/pg_duckdb/issues/93 ):
* keep a function with a pure C++ "flavor" (object creation, exceptions, etc.)
* call it in a new wrapper that copies out the error message and uses PG mechanism to throw the error

This fixes https://github.com/duckdb/pg_duckdb/issues/120, even though there still seem to be a small leak with DuckDB's `PrepareQuery` leftover (to be followed-up separately)

2024-10-09 09:31 UTC, JelteF approved these changes

2024-10-09 09:57 UTC, JelteF requested changes
Tests are still failing it seems after merging with main.

2024-10-09 10:11 UTC, Y-- commented
> Tests are still failing it seems after merging with main.

Yeah sorry should have kept this in draft - I'm still working on it; this is a simple revert

2024-10-10 11:13 UTC, JelteF approved these changes

2024-10-10 11:16 UTC, merged