Add issue template
duckdb/pg_duckdb pull request #301
Opened 2024-10-16 15:29 UTC by Y--

First version of issue template - largely inspired (copied) from DuckDB's repo
Fixes https://github.com/duckdb/pg_duckdb/issues/223

2024-10-16 16:20 UTC, wuputah reviewed
Thanks for starting on this. I think there's no way to preview this, but [looking at duckdb](https://github.com/duckdb/duckdb/issues/new?assignees=&labels=needs+triage&projects=&template=bug_report.yml) this looks quite heavy. For now, I think we want something closer to a template rather than a form - i.e. placeholder text that we can easily modify or delete when opening issues ourselves, rather than something this detailed with separate textareas. I think the form will probably drive us crazy. If we get to the point where we're creating the small minority of issues, this structure might make sense.

2024-10-16 16:20 UTC, wuputah commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Please report security vulnerabilities using GitHub's [report vulnerability form](https://github.com/duckdb/pg_duckdb/security/advisories/new).
seems like we'll need to turn something on here

2024-10-16 16:31 UTC, JelteF requested changes

2024-10-16 16:31 UTC, JelteF commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        * Add all required imports for scripts, e.g., `import duckdb`, `import pandas as pd`.
This line can be removed I think.
```suggestion
```

2024-10-16 16:31 UTC, JelteF commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        * If applicable, please check whether the issue is reproducible via running plain SQL queries from the DuckDB CLI client.
Doesn't really apply I think?
```suggestion
```

2024-10-16 16:31 UTC, JelteF commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: e.g., 16
```suggestion
      placeholder: e.g., 16.5
```

2024-10-16 16:31 UTC, JelteF commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: e.g., 22
We ship a fixed version of DuckDB with pg_duckdb, so pg_duckdb version should be enough.
```suggestion
    attributes:
      label: "pg_duckdb Version:"
      placeholder: e.g., 0.1.0
```

2024-10-16 16:31 UTC, JelteF commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?
```suggestion
      label: Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?
```

2024-10-16 16:40 UTC, JelteF commented
> I think the form will probably drive us crazy.

Totally agreed. I think that's easily solvable by adding a second issue template that we can choose, called something like "Issues reported by maintainers". As long as 90% of users will click the "Bug report" option we'll get the benefit of both.

2024-10-17 13:18 UTC, wuputah approved these changes

2024-10-17 14:09 UTC, JelteF approved these changes

2024-10-17 14:09 UTC, merged