Add tests for json operators
duckdb/pg_duckdb pull request #513
Opened 2024-12-31 13:57 UTC by ritwizsinha

Operators like `#>` and `#>>` are not supported in duckdb, adding tests for those

2025-01-02 12:08 UTC, JelteF requested changes
Thanks! These tests cover some nice ground around JSON support. Sadly half of them result in warnings at the moment, but I think it'd be good to add them already anyway. At least to make sure that we don't crash/error, but fall back gracefully to Postgres execution.

2025-01-02 12:10 UTC, JelteF commented on test/regression/expected/json_operator_support.out
> +WARNING:  (PGDuckDB/CreatePlan) Prepared query returned an error: 'Binder Error: No function matches the given name and argument types 'json_extract("UnsupportedPostgresType (Oid=3802)", VARCHAR)'. Y
It would be really good to start supporting JSONB.

2025-01-02 14:28 UTC, ritwizsinha commented on test/regression/expected/json_operator_support.out
> +select '{"a": {"b":"foo"}}'::json->'a'
Removed them

2025-01-12 22:10 UTC, JelteF commented on src/pgduckdb_types.cpp
> +	case JSONBOID:
We should also support jsonb insida a postgres array:

```suggestion
	case JSONBOID:
	case JSONBARRAYOID:
```

This would need some tests in array_type_support.sql

2025-01-12 22:11 UTC, JelteF commented on test/regression/sql/json_operator_support.sql
> +CREATE TABLE test_json (
Let's call this `test_jsonb`. I think it would be good to also have the same test for the actual postgres `JSON` type.

2025-01-12 22:12 UTC, JelteF commented on test/regression/schedule
> +test: json_operator_support
Let's change the name of the file now, since it's not specific to operators anymore. 
```suggestion
test: json_support
```

2025-01-13 07:25 UTC, ritwizsinha commented on test/regression/schedule
> +test: json_operator_support
Removed the file and added tests to type support and array type support

2025-01-13 07:25 UTC, ritwizsinha commented on src/pgduckdb_types.cpp
> +	case JSONBOID:
Done

2025-01-13 10:40 UTC, ritwizsinha commented
@JelteF your requested changes were made

2025-01-13 10:50 UTC, JelteF approved these changes
Thanks for this work. This looks good now. Next steps in my order of priority would be:

1. Start supporting some of duckdb its [JSON functions](https://duckdb.org/docs/data/json/json_functions)
2. Introduce some of the JSONB operators that postgres supports to DuckDB.
3. Introduce a PG compatibility mode in duckdb to make existing operators behave exactly the same.

2025-01-13 10:50 UTC, merged